---
# tasks file for vector
- name: Download & unarchive ## get_url пропущено, так как его функционал встроен в unarchive с 2.0 версии
  become: true
  ansible.builtin.unarchive:
    src: https://packages.timber.io/vector/{{ vector_version }}/vector-{{ vector_version }}-x86_64-apple-darwin.tar.gz
    dest: /usr/local/bin
    remote_src: true
  notify: Start vector service

- name: Configure Vector | ensure what directory exists
  become: true
  ansible.builtin.file:
    path: "{{ vector_config_dir }}"
    state: directory
    mode: "0755"
  tags: [config]
- name: Configure Vector | Template config
  become: true
  ansible.builtin.template:
    src: vector.yml.j2
    mode: "0755"
    dest: "{{ vector_config_dir }}/vector.yml"
  tags: [config]
- name: Configure Vector Service | Template systemd unit
  become: true
  ansible.builtin.template:
    src: vector.service.j2
    mode: "0755"
    dest: /etc/systemd/system/vector.service
  notify: Start vector service
  tags: [config]
